/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * user guide available at https://docs.gradle.org/5.0/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    `java-library`
    id("pl.allegro.tech.build.axion-release") version "1.10.0"
    id("org.sonarqube") version "2.7"
    jacoco
}

tasks.jacocoTestReport {
    reports {
        xml.isEnabled = true
        csv.isEnabled = false
    }
}



repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("org.hamcrest:hamcrest-core:2.1")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
    testImplementation("io.cucumber:cucumber-java8:4.2.6")
    testImplementation("io.cucumber:cucumber-junit:4.2.6")
    testImplementation("org.easytesting:fest-assert-core:2.0M10")
}
